First commit with the general parsing of inputs and execution of comm…
AY2021S2-CS2113T-F10-1/tp pull request #25
Opened 2021-03-07 18:39 UTC by heyjinwei

…and. Filter by price enabled.

2021-03-08 01:59 UTC, jadenwjh commented on src/main/java/seedu/hdbuy/HdBuy.java
> +            Command c =  parser.parse(fullCommand);
Consider using a more descriptive variable name other than 'c'

2021-03-08 02:05 UTC, heyjinwei commented on src/main/java/seedu/hdbuy/HdBuy.java
> +            Command c =  parser.parse(fullCommand);
Sorry, do you have any suggestions? haha because i just followed the example they gave on the week 7 project

2021-03-08 02:10 UTC, jadenwjh requested changes
Need to refactor some code. Code in main() can be refactored into another method to be run recursively. Might need to assign constant values to variables. Other than that, LGTM.

2021-03-08 02:10 UTC, jadenwjh commented on src/main/java/seedu/hdbuy/HdBuy.java
> +        while (!isExit) {
Consider refactoring this as a method so that u can run this recursively.

2021-03-08 02:10 UTC, jadenwjh commented on src/main/java/seedu/hdbuy/command/DefaultCommand.java
> +public class DefaultCommand extends Command {
Consider adding javadoc to describe the use of this method.

2021-03-08 02:10 UTC, jadenwjh commented on src/main/java/seedu/hdbuy/parser/Parser.java
> +        case "help":
Consider assigning a variable to constant values.
ie: private static final String FILTER = "filter";

2021-03-08 02:13 UTC, jadenwjh commented on src/main/java/seedu/hdbuy/HdBuy.java
> +            Command c =  parser.parse(fullCommand);
Command command = parser.parse...
Because single character names usually used for counter / index.

2021-03-09 15:14 UTC, heyjinwei commented on src/main/java/seedu/hdbuy/HdBuy.java
> +            Command c =  parser.parse(fullCommand);
okay will change accordingly. thank you

2021-03-09 15:26 UTC, heyjinwei commented on src/main/java/seedu/hdbuy/HdBuy.java
> +        while (!isExit) {
are u referring to the whole chunk of code inside the while loop? what would you recommend I call it?

2021-03-09 15:37 UTC, jadenwjh commented on src/main/java/seedu/hdbuy/HdBuy.java
> +        while (!isExit) {
Yup, perhaps init()?

2021-03-09 15:57 UTC, heyjinwei commented on src/main/java/seedu/hdbuy/HdBuy.java
> +        while (!isExit) {
okay thank you! done!

2021-03-09 15:58 UTC, heyjinwei commented on src/main/java/seedu/hdbuy/command/DefaultCommand.java
> +public class DefaultCommand extends Command {
okay done!

2021-03-09 15:58 UTC, heyjinwei commented on src/main/java/seedu/hdbuy/parser/Parser.java
> +        case "help":
good point! done!

2021-03-09 16:09 UTC, jadenwjh approved these changes

2021-03-09 16:09 UTC, merged